### ISSUE TITLE
OSError: Failed to create queue 1.

### ISSUE THREAD

**Issue by hamedsbt** [Kkevsterrr/geneva#44]
Hi, thank you for help in advance...

I get error ```OSError: Failed to create queue 1.```
Python: ```3.10.7```
Kernel: ```archlinux 5.19.12-arch1-1-amd64```
```
# python3 engine.py --server-port 80 --strategy "[TCP:flags:PA]-duplicate(tamper{TCP:dataofs:replace:10}(tamper{TCP:chksum:corrupt},),)-|" --log debug
/usr/lib/python3.10/site-packages/scapy/layers/ipsec.py:471: CryptographyDeprecationWarning: Blowfish has been deprecated
  cipher=algorithms.Blowfish,
/usr/lib/python3.10/site-packages/scapy/layers/ipsec.py:485: CryptographyDeprecationWarning: CAST5 has been deprecated
  cipher=algorithms.CAST5,
WARNING:[ENGINE] No environment ID given, one has been generated (parw9j5p)
DEBUG:[ENGINE] Engine created with strategy [TCP:flags:PA]-duplicate(tamper{TCP:dataofs:replace:10}(tamper{TCP:chksum:corrupt},),)-| \/ (ID parw9j5p) to port 80
DEBUG:[ENGINE] Configuring iptables rules
DEBUG:[ENGINE] iptables -A OUTPUT -p tcp --match tcp --dport 80 -j NFQUEUE --queue-num 2
DEBUG:[ENGINE] iptables -A INPUT -p tcp --match tcp --sport 80 -j NFQUEUE --queue-num 1
DEBUG:[ENGINE] iptables -A OUTPUT -p udp --match udp --dport 80 -j NFQUEUE --queue-num 2
DEBUG:[ENGINE] iptables -A INPUT -p udp --match udp --sport 80 -j NFQUEUE --queue-num 1
Traceback (most recent call last):
  File "/opt/anti_c/geneva-master/engine.py", line 470, in <module>
    main(vars(get_args()))
  File "/opt/anti_c/geneva-master/engine.py", line 454, in main
    with Engine(args["server_port"],
  File "/opt/anti_c/geneva-master/engine.py", line 130, in __enter__
    self.initialize_nfqueue()
  File "/opt/anti_c/geneva-master/engine.py", line 272, in initialize_nfqueue
    self.in_nfqueue.bind(self.in_queue_num, self.in_callback)
  File "netfilterqueue/_impl.pyx", line 270, in netfilterqueue._impl.NetfilterQueue.bind
OSError: Failed to create queue 1.

```

Another question:```Does geneva help me on https too?!```

**Comment by lepz0r** [comment]
Try to run geneva on `virtualenv` and install it's python dependencies on virtual environment as it needs specific version of `scapy` and `cryptography`

**Comment by Kkevsterrr** [comment]
Sorry for the delay: if this is on Arch, some users have reported needing to set up a liblibc.a link:
```
sudo ln -s -f /usr/lib64/libc.a /usr/lib64/liblibc.a 
```
I do not know if that is your problem: Arch is not a supported platform that we test with unfortunately. Let me know if this works!
