### ISSUE TITLE
geneva error: Traceback (most recent call last)

### ISSUE THREAD

**Issue by Msadr471** [Kkevsterrr/geneva#54]
Hi

```
python3 engine.py --server-port 80 --strategy "\/" --log debug

        PIP package scapy-python3 used to provide scapy3k, which was a fork from scapy implementing python3 compatibility since 2016. This package was included in some of the Linux distros under name of python3-scapy. Starting from scapy version 2.4 (released in March, 2018) mainstream scapy supports python3. To reduce any confusion scapy3k was renamed to kamene. 
You should use either pip package kamene for scapy3k (see http://github.com/phaethon/kamene for differences in use) or mainstream scapy (pip package scapy, http://github.com/secdev/scapy).  

Traceback (most recent call last):
  File "/home/msadr471/Documents/App/geneva/engine.py", line 28, in <module>
    import layers.packet
  File "/home/msadr471/Documents/App/geneva/layers/packet.py", line 4, in <module>
    import layers.layer
  File "/home/msadr471/Documents/App/geneva/layers/layer.py", line 8, in <module>
    from scapy.all import IP, RandIP, UDP, DNS, DNSQR, Raw, TCP, fuzz
  File "/home/msadr471/.local/lib/python3.10/site-packages/scapy/all.py", line 5, in <module>
    raise Exception(msg)
Exception: 
        PIP package scapy-python3 used to provide scapy3k, which was a fork from scapy implementing python3 compatibility since 2016. This package was included in some of the Linux distros under name of python3-scapy. Starting from scapy version 2.4 (released in March, 2018) mainstream scapy supports python3. To reduce any confusion scapy3k was renamed to kamene. 
You should use either pip package kamene for scapy3k (see http://github.com/phaethon/kamene for differences in use) or mainstream scapy (pip package scapy, http://github.com/secdev/scapy).  



```

```
sudo python3 engine.py --server-port 80 --strategy "\/" --log debug
Traceback (most recent call last):
  File "/home/msadr471/Documents/App/geneva/engine.py", line 22, in <module>
    from scapy.layers.inet import IP
ModuleNotFoundError: No module named 'scapy'
```

what is wrong with scapy?
How do I fix this?

**Comment by VwCSXg** [comment]
This looks like scapy is not installed in your python environment.

Did you follow the setup instructions to install the python dependencies?: `python3 -m pip install -r requirements.txt`

**Comment by Kaimar666** [comment]
这是一封自动回复邮件。已经收到您的来信。

**Comment by Kkevsterrr** [comment]
Yup, echoing @VwCSXg - it looks like you have scapy3k (scapy-python3) installed, but scapy added Python3 support natively a long time ago. Clear out scapy-python3 and install from the requirements.txt doc!
