### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: b'liblibc.a'

### ISSUE THREAD

**Issue by hamedsbt** [Kkevsterrr/geneva#57]
I'm triying to test Geneva on ArchLinux and I got error: FileNotFoundError: [Errno 2] No such file or directory: b'liblibc.a'

```
$sudo python3 engine.py --server-port 80 --strategy "[TCP:flags:PA]-duplicate(tamper{TCP:dataofs:replace:10}(tamper{TCP:chksum:corrupt},),)-|" --log debug
python3 engine.py --server-port 80 --strategy "[TCP:flags:PA]-duplicate(tamper{TCP:dataofs:replace:10}(tamper{TCP:chksum:corrupt},),)-|" --log debug
Traceback (most recent call last):
  File "/opt/Geneva/geneva/engine.py", line 22, in <module>
    from scapy.layers.inet import IP
  File "/opt/home/user01/.local/lib/python3.10/site-packages/scapy/layers/inet.py", line 25, in <module>
    from scapy.layers.l2 import Ether, Dot3, getmacbyip, CookedLinux, GRE, SNAP, \
  File "/opt/home/user01/.local/lib/python3.10/site-packages/scapy/layers/l2.py", line 17, in <module>
    from scapy.ansmachine import AnsweringMachine
  File "/opt/home/user01/.local/lib/python3.10/site-packages/scapy/ansmachine.py", line 16, in <module>
    from scapy.sendrecv import send, sniff
  File "/opt/home/user01/.local/lib/python3.10/site-packages/scapy/sendrecv.py", line 35, in <module>
    import scapy.route  # noqa: F401
  File "/opt/home/user01/.local/lib/python3.10/site-packages/scapy/route.py", line 194, in <module>
    conf.route = Route()
  File "/opt/home/user01/.local/lib/python3.10/site-packages/scapy/route.py", line 27, in __init__
    self.resync()
  File "/opt/home/user01/.local/lib/python3.10/site-packages/scapy/route.py", line 33, in resync
    from scapy.arch import read_routes
  File "/opt/home/user01/.local/lib/python3.10/site-packages/scapy/arch/__init__.py", line 28, in <module>
    from scapy.arch.bpf.core import get_if_raw_addr
  File "/opt/home/user01/.local/lib/python3.10/site-packages/scapy/arch/bpf/core.py", line 31, in <module>
    LIBC = cdll.LoadLibrary(find_library("libc"))
  File "/usr/lib/python3.10/ctypes/util.py", line 330, in find_library
    _get_soname(_findLib_gcc(name)) or _get_soname(_findLib_ld(name))
  File "/usr/lib/python3.10/ctypes/util.py", line 147, in _findLib_gcc
    if not _is_elf(file):
  File "/usr/lib/python3.10/ctypes/util.py", line 99, in _is_elf
    with open(filename, 'br') as thefile:
FileNotFoundError: [Errno 2] No such file or directory: b'liblibc.a'

```

I have been installed all requirements.txt:
```
python3 -m pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pytest in /opt/home/solon/.local/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (7.1.3)
Requirement already satisfied: scapy==2.4.3 in /opt/home/solon/.local/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (2.4.3)
Requirement already satisfied: requests in /usr/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (2.28.2)
Requirement already satisfied: dnspython in /usr/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (2.3.0)
Requirement already satisfied: docker in /opt/home/solon/.local/lib/python3.10/site-packages (from -r requirements.txt (line 5)) (6.0.0)
Requirement already satisfied: anytree in /usr/lib/python3.10/site-packages (from -r requirements.txt (line 6)) (2.8.0)
Requirement already satisfied: graphviz in /opt/home/solon/.local/lib/python3.10/site-packages (from -r requirements.txt (line 7)) (0.20.1)
Requirement already satisfied: netifaces in /usr/lib/python3.10/site-packages (from -r requirements.txt (line 8)) (0.11.0)
Requirement already satisfied: netfilterqueue in /opt/home/solon/.local/lib/python3.10/site-packages (from -r requirements.txt (line 9)) (1.0.0)
Requirement already satisfied: cryptography==3.3.2 in /opt/home/solon/.local/lib/python3.10/site-packages (from -r requirements.txt (line 10)) (3.3.2)
Requirement already satisfied: paramiko in /opt/home/solon/.local/lib/python3.10/site-packages (from -r requirements.txt (line 11)) (2.11.0)
Requirement already satisfied: codecov in /opt/home/solon/.local/lib/python3.10/site-packages (from -r requirements.txt (line 12)) (2.1.12)
Requirement already satisfied: pytest-cov in /opt/home/solon/.local/lib/python3.10/site-packages (from -r requirements.txt (line 13)) (4.0.0)
Requirement already satisfied: tld in /opt/home/solon/.local/lib/python3.10/site-packages (from -r requirements.txt (line 15)) (0.12.6)
Requirement already satisfied: python-dotenv in /opt/home/solon/.local/lib/python3.10/site-packages (from -r requirements.txt (line 16)) (0.21.0)
Requirement already satisfied: mysql-connector in /opt/home/solon/.local/lib/python3.10/site-packages (from -r requirements.txt (line 17)) (2.2.9)
Requirement already satisfied: beautifulsoup4 in /usr/lib/python3.10/site-packages (from -r requirements.txt (line 18)) (4.11.2)
Requirement already satisfied: psutil in /usr/lib/python3.10/site-packages (from -r requirements.txt (line 20)) (5.9.4)
Requirement already satisfied: tqdm in /opt/home/solon/.local/lib/python3.10/site-packages (from -r requirements.txt (line 21)) (4.65.0)
Requirement already satisfied: six>=1.4.1 in /usr/lib/python3.10/site-packages (from cryptography==3.3.2->-r requirements.txt (line 10)) (1.16.0)
Requirement already satisfied: cffi>=1.12 in /usr/lib/python3.10/site-packages (from cryptography==3.3.2->-r requirements.txt (line 10)) (1.15.1)
Requirement already satisfied: tomli>=1.0.0 in /usr/lib/python3.10/site-packages (from pytest->-r requirements.txt (line 1)) (2.0.1)
Requirement already satisfied: py>=1.8.2 in /opt/home/solon/.local/lib/python3.10/site-packages (from pytest->-r requirements.txt (line 1)) (1.11.0)
Requirement already satisfied: iniconfig in /opt/home/solon/.local/lib/python3.10/site-packages (from pytest->-r requirements.txt (line 1)) (1.1.1)
Requirement already satisfied: packaging in /usr/lib/python3.10/site-packages (from pytest->-r requirements.txt (line 1)) (23.0)
Requirement already satisfied: attrs>=19.2.0 in /opt/home/solon/.local/lib/python3.10/site-packages (from pytest->-r requirements.txt (line 1)) (21.4.0)
Requirement already satisfied: pluggy<2.0,>=0.12 in /opt/home/solon/.local/lib/python3.10/site-packages (from pytest->-r requirements.txt (line 1)) (1.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3.10/site-packages (from requests->-r requirements.txt (line 3)) (1.26.13)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.10/site-packages (from requests->-r requirements.txt (line 3)) (3.4)
Requirement already satisfied: websocket-client>=0.32.0 in /opt/home/solon/.local/lib/python3.10/site-packages (from docker->-r requirements.txt (line 5)) (1.5.1)
Requirement already satisfied: bcrypt>=3.1.3 in /opt/home/solon/.local/lib/python3.10/site-packages (from paramiko->-r requirements.txt (line 11)) (4.0.0)
Requirement already satisfied: pynacl>=1.0.1 in /opt/home/solon/.local/lib/python3.10/site-packages (from paramiko->-r requirements.txt (line 11)) (1.5.0)
Requirement already satisfied: coverage in /opt/home/solon/.local/lib/python3.10/site-packages (from codecov->-r requirements.txt (line 12)) (6.5.0)
Requirement already satisfied: soupsieve>1.2 in /usr/lib/python3.10/site-packages (from beautifulsoup4->-r requirements.txt (line 18)) (2.4)
Requirement already satisfied: pycparser in /usr/lib/python3.10/site-packages (from cffi>=1.12->cryptography==3.3.2->-r requirements.txt (line 10)) (2.21)

```
Linux user01-pc 6.2.12-arch1-1 

Any help is appreciated.

**Comment by brigxt0** [comment]
Same issue for me on Kali rolling.Any way forward ?

**Comment by hamedsbt** [comment]
solution is:
```
sudo ln -s -f /usr/lib64/libc.a /usr/lib64/liblibc.a 
```

**Comment by Kkevsterrr** [comment]
Thanks for helping debug this - I'll amend the REAMDE to help future developers.
