### ISSUE TITLE
Ubuntu Python3.6 | undefined symbol: PyModule_Create2

### ISSUE THREAD

**Issue by kero3009destiny** [Kkevsterrr/geneva#70]
```bash
root@dirt-n745wu:/home/dirt/geneva# python3.6 engine.py
/usr/local/lib/python3.6/site-packages/scapy/config.py:384: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.6.
  import cryptography
/usr/local/lib/python3.6/site-packages/scapy/layers/ipsec.py:469: CryptographyDeprecationWarning: Blowfish has been deprecated
  cipher=algorithms.Blowfish,
/usr/local/lib/python3.6/site-packages/scapy/layers/ipsec.py:483: CryptographyDeprecationWarning: CAST5 has been deprecated
  cipher=algorithms.CAST5,
Traceback (most recent call last):
  File "engine.py", line 29, in <module>
    import actions.strategy
  File "/home/dirt/geneva/actions/strategy.py", line 3, in <module>
    import actions.utils
  File "/home/dirt/geneva/actions/utils.py", line 21, in <module>
    import plugins.plugin_server
  File "/home/dirt/geneva/plugins/plugin_server.py", line 5, in <module>
    import psutil
  File "/usr/local/lib/python3.6/site-packages/psutil/__init__.py", line 103, in <module>
    from . import _pslinux as _psplatform
  File "/usr/local/lib/python3.6/site-packages/psutil/_pslinux.py", line 25, in <module>
    from . import _psutil_linux as cext
ImportError: /usr/local/lib/python3.6/site-packages/psutil/_psutil_linux.abi3.so: undefined symbol: PyModule_Create2
```

**Comment by Kaimar666** [comment]
这是一封自动回复邮件。已经收到您的来信。
